version: '3'

services:
  db:
    image: mongo
    container_name: mongo-pokedex
    restart: always
    environment:
     # MONGO_INITDB_ROOT_USERNAME: "root"
      #MONGO_INITDB_ROOT_PASSWORD: "12345678"
      MONGO_DATABASE: nest-pokemon
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: {}